services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Mir\HeadlessCache\:
    resource: '../Classes/*'

  Mir\HeadlessCache\DataHandling\DataHandlerHook:
    public: true
  