base: 'https://t3-forms.ddev.site'
dependencies:
  - typo3/form
  - t13-forms/sitepackage
  - lochmueller/seal
  - t13/meetups
  - typo3/felogin
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: ''
rootPageId: 1
sealAutocompleteMinCharacters: '3'
sealItemsPerPage: '10'
sealPaginationClass: TYPO3\CMS\Core\Pagination\SimplePagination
sealPaginationMaximumNumberOfLinks: '6'
sealSearchDsn: 'typo3://'
routeEnhancers:
  MeetupsPlugin:
    type: Extbase
    extension: Meetups
    plugin: Event
    routes:
      - routePath: '/meetups'
        _controller: 'Event::list'
      - routePath: '/meetups/page-{page}'
        _controller: 'Event::list'
        _arguments:
          page: currentPage
        requirements:
          page: '\d+'
      - routePath: '/meetup/{event}'
        _controller: 'Event::show'
        _arguments:
          event: event
    defaultController: 'Event::list'
    aspects:
      event:
        type: PersistedAliasMapper
        tableName: tx_meetups_domain_model_event
        routeFieldName: title
        routeValuePrefix: ''
websiteTitle: ''
